# Generated by Django 4.1.7 on 2024-07-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Acercade', models.TextField()),
                ('foto', models.ImageField(upload_to='acercade/')),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('git', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AcercaDe',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='proyecto', to='Home.habilidad'),
        ),
    ]
