# Generated by Django 4.1.7 on 2024-07-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contacto_delete_acercade_alter_proyecto_tecnologias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tecnologias',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
