# Generated by Django 4.1.7 on 2024-07-30 19:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0003_delete_contacto_remove_proyecto_tecnologias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('acercade', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='acercade/')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('git', models.URLField()),
                ('linkedin', models.URLField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('tiempo_experiencia', models.PositiveIntegerField(help_text='Experiencia en años')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='habilidades/')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='proyectos', to='Home.habilidad')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha'],
            },
        ),
    ]
